# @misc{Rickstaa, 
#title={RICKSTAA/action-black: Runs the PSF/black formatter to check/format your python code.}, 
#url={https://github.com/rickstaa/action-black}, 
#journal={GitHub}, 
#author={Rickstaa}
#} 

name: Python File Linter

on: [pull_request]

jobs:
  linter_name:
    name: runner / black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Black Formatter
        uses: rickstaa/action-black@v1
        id: action_black
        with:
          black_args: "."
      - uses: stefanzweifel/git-auto-commit-action@v4
        name: "Attempt to Auto fix black formatter issues"
        if: steps.action_black.outputs.is_formatted == 'true'
        with:
          commit_message: ":art: Format Python code with psf/black"
          commit_options: "--no-verify"
          commit_user_name: github-actions
          commit_user_email: ghaction@github.com